1. [[Оповещения от комунальных служб]]
2. [[Оповещения ДЛ]]
3. Оповещения по адресу происшествия
Различались адреса указанные у пользователя в базе и в событии
```python
addresses = 'ул. Регатная, 4, г. Красноярск'
с = 'Россия, Красноярский край, г. Красноярск, ул. Регатная, 4'
```
Я привел адреса к примерно одному виду: улица, дом, город
Проблема проверки была в том, что адреса могли записываться в таком виде
```python
addresses = 'ул. Регатная, 4, г. Красноярск|||ул. Регатная, 5, г. Красноярск'
```
И проверку по 1 адресу у пользователя и в происшествии сделал так
```python
broadcast_communal_address = broadcast.communal.incident_address
split_addresses = broadcast_communal_address.split("|||")
formatted_addresses = []
for addresses in split_addresses:
	parts = addresses.split(", ")
	formatted_address = f"{parts[3]}, {parts[4]}, {parts[2]}"
	formatted_addresses.append(formatted_address)

query = Q()
for i in formatted_addresses:
	query |= Q(user__addresses__icontains=i)
	
	# Для каждого элемента создается объект `Q` для фильтрации пользователей, чье поле `addresses` содержит этот конкретный адрес. Оператор `|=` используется для выполнения побитовой операции ИЛИ с существующим объектом `query`.
	
active_subscriptions = active_subscriptions.filter(query)
```

2. Работа пушей при отправке сообщений ДЛ.
Надо для начала посмотреть `task` 
```python
@celery_app.task(name='officialsnotification.tasks.worker')
	def worker():```
В ней вызывается функция 
```python
def start_broadcast(notification)
```
В ней происходит создание истории оповещения, затем отправка по PUSH, отправка по EMAIL
Отправка по PUSH происходит в функции `start_sending_push(notification)`
Готовится сообщение и отправляется на отдельный сервис (channel-push в докер-композе)
```python
def send_messages_push(messages, multi=False):

	logger = get_task_logger(__name__)
	logger.info("Sending messages via push.")
	push_url = AbstractBroadcastAccessPoint.PUSH
	...
	response = requests.post(f"{push_url}/api/send", json=request_data)
	...
```
В сервис возвращает ответ и по этому ответу либо сообщение отправилось и все хорошо, либо ошибка отправки и приходит сообщение с fail 
```python
Response text is {"code": 0, "data": {"status": "completed", "sent": [], "fail": ["7c5270a3-8ca8-48cf-bbc9-6eba497a9404"]}}
```
В этом случае происходит смена канала отправки с push на email
```python
switch_broadcast_channel_from_push_to_email_in_broadcast_histories(
	notification,
	AbstractBroadcastChannel.PUSH,
	AbstractBroadcastChannel.EMAIL,
	failed_device_ids
)
```
и дальше идет отправка по каналу EMAIL
