Напишем функцию вызывающую наши новые кастомные ошибки
```async def read_item(item_id: int):
    if item_id == 42:
        raise CustomExceptionA(detail="Item not found", status_code=404, message="You're trying to get an item that doesn't exist. Try entering a different item_id.")
    raise CustomExceptionB
```

Далее создаем Pydantic класс для обработки ошибки

```
class CustomExceptionModel(BaseModel):
	status_code: str
	er_message: str
	er_datails: str
```

Добавим кастомное поле в новый класс обработки ошибок

```
class CustomExceptionA(HTTPException):
	def __init__(self, detail: str, status_code: int, message: str):
	super().__init__(status_code=status_code, detail=detail)
	self.message = message
```

Добавим наш новый класс в обработчики
```
from fastapi.encoders import jsonable_encoder


@app.exception_handler(CustomExceptionA)
async def custom_exception(request: Request, exc: CustomExceptionA)
# Тут используем модель
error = jsonable_encoder(CustomExceptionModel(
	status_code=exc.status_code,
	er_message=exc.message,
	er_details=exc.detail
	)
)
return JSONResponse(status_code=exc.status_code, content=error)
```

Затем все вызывется в функции