Чтобы обработать стандартную обработку ошибок валидации при некорректных данных переданных в ручку

```python
from fastapi import FastAPI, HTTPException
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel

app = FastAPI()

# кастомный обработчик исключения для всех HTTPException
async def custom_http_exception_handler(request, exc):
    return JSONResponse(
        status_code=exc.status_code,
        content={"error": str(exc)},
    )

# кастомный обработчик исключения для RequestValidationError (Pydantic validation errors - 422 Unprocessable Entity) -> Это обработает стандартную ошибку
async def custom_request_validation_exception_handler(request, exc):
    return JSONResponse(
        status_code=422,
        content={"message": "Custom Request Validation Error", "errors": exc.errors()},
    )

# тут показываем альтернативный декораторам способ регистрации хэндлеров
app.add_exception_handler(HTTPException, custom_http_exception_handler)
app.add_exception_handler(RequestValidationError, custom_request_validation_exception_handler)
```


Однако можно и сделать доп условия валидации прямо в модели
```python
from typing import Union
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, field_validator

class Item(BaseModel):
    name: str
    description: Union[str, None] = None
    price: float
    tax: Union[float, None] = None

    @field_validator("price")
    @classmethod
    def validate_price(cls, value):
        if value < 0:
            raise ValueError("Price must be non-negative")
        return value

app = FastAPI()

@app.post("/items/")
async def create_item(item: Item):
    return {"message": "Item created successfully", "item": item}
```
